### ISSUE TITLE
file location?

### ISSUE THREAD

**Issue by dchubad** [playay/ws2s#10]
(all files are store in ~/.ws2s/)
where the hell is  ~/.ws2s/ ??? I can not find this directory to edit the config file. I am using windows 11 OS

**Comment by playay** [comment]
seems that Windows OS is not supported。 Even if you find the configuration file, you may not be able to run it In subsequent steps。

**Comment by playay** [comment]
`~` Represents the user directory. may be something like `C:\Users\<your username>`

**Comment by dchubad** [comment]
> seems that Windows OS is not supported。 Even if you find the configuration file, you may not be able to run it In subsequent steps。

ok thank you

**Comment by playay** [comment]
> > seems that Windows OS is not supported。 Even if you find the configuration file, you may not be able to run it In subsequent steps。
> 
> ok thank you

such as : `os.fork()` is used for  `start` cmd to run this program as a daemon,  but windows does not support `fork`.
