### ISSUE TITLE
WS2S Client Seems Incompatible on a Windows Machine

### ISSUE THREAD

**Issue by 19UV** [playay/ws2s#5]
While attempting to execute either of the client examples on a Windows machine, WebSocket throws a "net::ERR_CERT_DATE_INVALID".

Are there any known solutions?

**Comment by playay** [comment]
examples in readme.md use “ws2s.feling.io”， this domain is no longer in use。new domain is “ws2s.feling.net”。

**Comment by 19UV** [comment]
Problem fixed. Thanks.
