### ISSUE TITLE
Accept unmasked connections

### ISSUE THREAD

**Issue by benny1611** [playay/ws2s#7]
Hi,
is there a way that I can make ```ws2s``` skip the mask verification and accept unmasked connection? I ran into some trouble with a library. It has a "bug", it doesn't mask the payload and the connection is refused every time I try to connect. Until this bug is fixed, I need a way to test my program. Can I tell ```ws2s``` to accept unmasked connections? Thanks!

**Comment by playay** [comment]
https://github.com/playay/ws2s/blob/master/ws2s/websocket_server.py   
read_next_message()

You need to  get familiar with the websocket protocol, and modify read_next_message() method in websocket_server.py，especially line 206~209， line 222

**Comment by benny1611** [comment]
I've already done that, and it worked fine, but in the meantime the buggy software that I was using has been patched.
